# For bundler
source "http://rubygems.org"
source "http://gems.github.com" # for thoughtbot-clearance

group :default do
  gem "rails", "2.3.5"
    gem "activesupport", "2.3.5"
    gem "activerecord", "2.3.5"
    gem "activeresource", "2.3.5"
    gem "actionpack", "2.3.5"
    gem "actionmailer", "2.3.5"
    gem "rack", "1.0.1"
  gem "sinatra", "1.0"
  gem "packet", "0.1.15"
  gem "thoughtbot-clearance", "0.6.9", :require => "clearance"
  gem "fastercsv", "1.5.0"
  gem "prawn", "0.8.4"
    gem "prawn-core", "0.8.4"
    gem "prawn-layout", "0.8.4"
    gem "prawn-security", "0.8.4"
  gem "hpricot", "0.6"
  gem "thoughtbot-paperclip", "2.3.0", :require => "paperclip"
  gem "httparty", "0.4.4"
  gem "crack", "0.1.8"
  gem "chronic", "0.2.3"
    gem "json_pure", "1.4.3"
    gem "rubyforge", "2.0.4"
    gem "hoe", "2.6.1"
  gem "validatable", "1.6.7"
  gem "bullet", "1.7.6"
  gem "ruby-growl", "2.0"
  gem "will_paginate", "2.3.14"
  gem "RedCloth", "4.2.3"
  gem "hoptoad_notifier", "2.3.0"
  gem "pauldix-feedzirra", "0.0.18"
    gem "builder", "2.1.2"
    gem "nokogiri", "1.4.3.1"
    gem "mdalessio-dryopteris", "0.1.2"
    gem "pauldix-sax-machine", "0.0.14"
    gem "taf2-curb", "0.5.4.0"
  gem "mysql", "2.8.1"
  gem "libxml-ruby", "1.1.3"
#  gem "slim_scrooge", "1.0.10"
end

group :test do
  gem "rspec", "1.3.0", :require => "spec"
  gem "rspec-rails", "1.3.2"
  gem "thoughtbot-factory_girl", "1.2.2", :require => "factory_girl"
  gem "webrat", "0.7.1"
    gem "rack-test", "0.5.4"
end

group :cucumber do
  gem "cucumber", "0.8.5"
    gem "diff-lcs", "1.1.2"
    gem "trollop", "1.16.2"
    gem "gherkin", "2.1.5"
    gem "term-ansicolor", "1.0.5"
  gem "cucumber-rails", "0.3.2"
  gem "database_cleaner", "0.5.0"
  gem "spork", "0.8.4"

  gem "culerity", "0.2.4"
  gem "mime-types", "1.16"
  gem "nokogiri", "1.4.3.1"
  gem "rack-test", "0.5.4"
  gem "rspec", "1.3.0"
  gem "selenium-webdriver", "0.0.3"
  gem "sinatra", "1.0"
  gem "capybara", "0.3.9"
end

group :tools do
  gem "launchy"
  gem "capistrano"
  gem "git"
  gem "git_remote_branch"
  gem "ruby-debug"
end
