source "http://rubygems.org"
source "http://gems.github.com" # for thoughtbot-clearance
gem "rails", "2.3.5"
  gem "activesupport", "2.3.5"
  gem "activerecord", "2.3.5"
  gem "activeresource", "2.3.5"
  gem "actionpack", "2.3.5"
  gem "actionmailer", "2.3.5"
  gem "rack", "1.0.1"
gem "sinatra", "1.0"
gem "packet", "0.1.15"
gem "thoughtbot-clearance", "0.6.9"
gem "fastercsv", "1.5.0"
gem "prawn", "0.8.4"
  gem "prawn-core", "0.8.4"
  gem "prawn-layout", "0.8.4"
  gem "prawn-security", "0.8.4"
gem "hpricot", "0.6"
gem "thoughtbot-paperclip", "2.3.0"
gem "httparty", "0.4.4"
gem "crack", "0.1.8"
gem "chronic", "0.2.3"
  gem "json_pure", "1.4.3"
  gem "rubyforge", "2.0.4"
  gem "hoe", "2.6.1"
gem "validatable", "1.6.7"
