Feature: Sending alerts to short message devices

  In order to ....
  As a ...
  I want to ....

  Scenario: Sending an alert with a short message to communication devices that accept short messages
  
