permitted_mimes: 
    - image/jpeg 
    - image/gif 
    - image/png 
    - image/svg+xm 
    - image/x-icon 
    - image/bmp 
    - application/pdf 
    - application/rtf
    - text/plain 
    - text/richtext 
    - application/x-compressed 
    - application/x-gzip 
    - application/x-stuffit 
    - application/x-tar
    - application/zip
    - audio/mid 
    - audio/wav 
    - audio/mpeg 
    - video/mpeg 
    - video/quicktime 
    - video/x-ms-asf 
    - video/msvideo 
    - application/msword 
    - application/vnd.ms-excel 
    - application/vnd.ms-outlook 
    - application/vnd.ms-powerpoint 
    - application/vnd.ms-works 
    - application/x-mswrite 
