permitted_mimes:
    - image/jpeg
    - image/pjpeg
    - image/gif
    - image/png
    - image/x-png
    - image/tiff
    - image/svg+xml
    - image/x-icon
    - image/bmp
    - application/pdf
    - application/rtf
    - text/plain
    - text/richtext
    - text/csv
    - text/html
    - application/x-compressed
    - application/x-gzip
    - application/x-stuffit
    - application/x-tar
    - application/x-rar
    - application/zip
    - audio/mid
    - audio/wav
    - audio/x-wav
    - audio/mpeg
    - video/mpeg
    - video/quicktime
    - video/x-ms-asf
    - video/msvideo
    - video/dv
    - video/h264
    - video/mp4
    - application/dxf
    - application/msword
    - application/vnd.ms-word
    - application/vnd.ms-excel
    - application/vnd.ms-outlook
    - application/vnd.ms-office
    - application/vnd.ms-powerpoint
    - application/vnd.ms-works
    - application/x-mswrite
    - application/vnd.openxmlformats-officedocument.presentationml.presentation
    - application/vnd.openxmlformats-officedocument.wordprocessingml.template
    - message/rfc822
rejected_extensions:
    - .applescript
    - .as
    - .asp
    - .aspx
    - .bat
    - .cgi
    - .com
    - .csh
    - .exe
    - .json
    - .js
    - .msi
    - .php
    - .phtml
    - .php5
    - .phps
    - .pl
    - .py
    - .pyw
    - .pyo
    - .pyc
    - .pyd
    - .rb
    - .rbw
    - .scpt
    - .sh
    - .sql
    - .tcl
    - .vbs
    - .vbe
    - .wsf
    - .wsc
