# 1) application will use the config where 'domain' matches request.domain or fall back to 'default'
# 2) logo_image expects a PNG;  see initializers/dashboard.rb
# 3) sign_in_partial will render a partial by that name in views/sessions/
# 4) new_user_path will redirect_to the given route

-
    domain: facho.talho.org
    sign_in_partial: facho_sign_in
    new_user_path: new_facho_user
    logo_image: images/talho_header_logo.png
    help_email: admins@talho.org
    about_button_label: About FACHO Dashboard
    about_button_url: /about_talhophin
-
    domain: default
    sign_in_partial: talho
    logo_image: images/talho_header_logo.png
    help_email: admins@talho.org
    about_button_label: About TALHO Phin
    about_button_url: /about_talhophin