load "db/fixtures/apps.rb"
load "db/fixtures/roles.rb"
load "db/fixtures/jurisdictions.rb"
load "db/fixtures/users.rb"
load "db/fixtures/organizations.rb"
load "db/fixtures/articles.rb"
load "db/fixtures/dashboards.rb"
